name: Artifact

on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'runs-on'
        required: true
        type: choice
        options:
        - ubuntu-latest
        - windows-latest
        - macos-latest

jobs:
  build_artifact:
    runs-on: ${{ inputs.runner }}
    name: Export artifact for ${{ inputs.runner }}
    steps:
      - name: libMVRGdtf - checkout repository
        uses: actions/checkout@v4
        with:
          path: libMvrGdtf
      
      - name: Build Linux
        if: inputs.runner == 'ubuntu-latest'
        uses: ./libMvrGdtf/.github/actions/build-ubuntu
        
      - name: Build Windows
        if: inputs.runner == 'windows-latest'
        uses: ./libMvrGdtf/.github/actions/build-windows
        
      - name: Build Windows
        if: inputs.runner == 'macos-latest'
        uses: ./libMvrGdtf/.github/actions/build-macos

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libMVRgdtf-${{ inputs.runner }}
          path: |
            libMvrGdtf/output
