# Name of our action
name: Release

on:
  workflow_dispatch:

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository under ./libMvrGdtf
        uses: actions/checkout@v4
        with:
          path: libMvrGdtf
          fetch-depth: 0
          fetch-tags: true

      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        uses: ./libMvrGdtf/.github/actions/build-linux

      - name: Build Windows
        if: matrix.os == 'windows-latest'
        uses: ./libMvrGdtf/.github/actions/build-win32

      - name: Release OS
        uses: ./libMvrGdtf/.github/actions/release-os
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_PKG_KEY }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_PKG_KEY}}
