# Name of our action
name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository under ./libMvrGdtf
        uses: actions/checkout@v4
        with:
          path: libMvrGdtf
          fetch-depth: 0
          fetch-tags: true

      # - name: Build
      #   uses: ./libMvrGdtf/.github/actions/build-linux

      - name: Add .npmrc
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PKG_KEY}}
        run: |
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          echo "@mvrdevelopment:registry=https://npm.pkg.github.com/" >> ~/.npmrc
      
      - name: Mock github user
        run: |
          git config --global user.email "simorolev@gmail.com"
          git config --global user.name "Simeon Rolev"

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_PKG_KEY }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_PKG_KEY}}
        working-directory: libMvrGdtf
        run: |
          git checkout -b release/linux
          node scripts/json-updater.js --name @mvrdevelopment/lib-gdtf-linux  --os "linux" --files "package.json"
          npm version patch --no-git-tag-version
          git add .
          git commit -m "Package prepare"

          npm install
          npm publish --dry-run
